
package mypackage;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PersonServicePortType", targetNamespace = "http://www.groept.be/PersonService/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PersonServicePortType {


    /**
     * 
     * @param address
     * @param name
     * @param age
     */
    @WebMethod(operationName = "SendPerson")
    @Oneway
    @RequestWrapper(localName = "SendPerson", targetNamespace = "http://www.groept.be/PersonService/", className = "mypackage.SendPerson")
    public void sendPerson(
        @WebParam(name = "Name", targetNamespace = "http://www.groept.be/PersonService/")
        String name,
        @WebParam(name = "Age", targetNamespace = "http://www.groept.be/PersonService/")
        int age,
        @WebParam(name = "Address", targetNamespace = "http://www.groept.be/PersonService/")
        mypackage.SendPerson.Address address);

}
