
package exerciceone;

import java.math.BigDecimal;
import java.util.List;
import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "OrderServicePortType", targetNamespace = "http://www.example.org/TopDown/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface OrderServicePortType {


    /**
     * 
     * @param totalOrderPrice
     * @param orderDate
     * @param orderName
     * @param products
     */
    @WebMethod(operationName = "SaveOrder")
    @Oneway
    @RequestWrapper(localName = "SaveOrder", targetNamespace = "http://www.example.org/TopDown/", className = "exerciceone.SaveOrder")
    public void saveOrder(
        @WebParam(name = "orderName", targetNamespace = "http://www.example.org/TopDown/")
        String orderName,
        @WebParam(name = "orderDate", targetNamespace = "http://www.example.org/TopDown/")
        XMLGregorianCalendar orderDate,
        @WebParam(name = "totalOrderPrice", targetNamespace = "http://www.example.org/TopDown/")
        BigDecimal totalOrderPrice,
        @WebParam(name = "products", targetNamespace = "http://www.example.org/TopDown/")
        List<exerciceone.SaveOrder.Products> products);

}
